// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Permission struct {
	ID         pgtype.UUID `json:"id"`
	Action     string      `json:"action"`
	ResourceID pgtype.UUID `json:"resource_id"`
}

type Resource struct {
	ID   pgtype.UUID `json:"id"`
	Code string      `json:"code"`
}

type Role struct {
	ID   pgtype.UUID `json:"id"`
	Code string      `json:"code"`
}

type RolePermission struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

type User struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
	RoleID   pgtype.UUID `json:"role_id"`
	Blocked  bool        `json:"blocked"`
}
