// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (id, code)
VALUES ($1, $2)
RETURNING id, code
`

type CreateRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Code string      `json:"code"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.ID, arg.Code)
	var i Role
	err := row.Scan(&i.ID, &i.Code)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password, role_id, blocked)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password, role_id, blocked
`

type CreateUserParams struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
	RoleID   pgtype.UUID `json:"role_id"`
	Blocked  bool        `json:"blocked"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.RoleID,
		arg.Blocked,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.RoleID,
		&i.Blocked,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getPermissionsByRoleID = `-- name: GetPermissionsByRoleID :many
SELECT p.id, p.action, p.resource_id
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
`

func (q *Queries) GetPermissionsByRoleID(ctx context.Context, roleID pgtype.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getPermissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Action, &i.ResourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourceByCode = `-- name: GetResourceByCode :one
SELECT id, code FROM resources WHERE code = $1
`

func (q *Queries) GetResourceByCode(ctx context.Context, code string) (Resource, error) {
	row := q.db.QueryRow(ctx, getResourceByCode, code)
	var i Resource
	err := row.Scan(&i.ID, &i.Code)
	return i, err
}

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT id, code FROM roles WHERE code = $1
`

func (q *Queries) GetRoleByCode(ctx context.Context, code string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByCode, code)
	var i Role
	err := row.Scan(&i.ID, &i.Code)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, code FROM roles WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(&i.ID, &i.Code)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, role_id, blocked FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.RoleID,
		&i.Blocked,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password, role_id, blocked FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.RoleID,
		&i.Blocked,
	)
	return i, err
}

const hasAccess = `-- name: HasAccess :one
SELECT EXISTS (
    SELECT 1
    FROM roles r
    WHERE r.id = $1
      AND (
        r.code = 'supermanager'
        OR EXISTS (
            SELECT 1
            FROM role_permissions rp
            JOIN permissions p ON rp.permission_id = p.id
            JOIN resources res ON p.resource_id = res.id
            WHERE rp.role_id = r.id
              AND p.action = $2
              AND res.code = $3
        )
      )
) AS has_access
`

type HasAccessParams struct {
	ID     pgtype.UUID `json:"id"`
	Action string      `json:"action"`
	Code   string      `json:"code"`
}

func (q *Queries) HasAccess(ctx context.Context, arg HasAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasAccess, arg.ID, arg.Action, arg.Code)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2,
    password = $3,
    role_id = $4,
    blocked = $5
WHERE id = $1
RETURNING id, email, password, role_id, blocked
`

type UpdateUserParams struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
	RoleID   pgtype.UUID `json:"role_id"`
	Blocked  bool        `json:"blocked"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.RoleID,
		arg.Blocked,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.RoleID,
		&i.Blocked,
	)
	return i, err
}
