// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password, role_id, blocked)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password, role_id, blocked
`

type CreateUserParams struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
	RoleID   pgtype.UUID `json:"role_id"`
	Blocked  bool        `json:"blocked"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.RoleID,
		arg.Blocked,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.RoleID,
		&i.Blocked,
	)
	return i, err
}

const getPermissionsByRoleID = `-- name: GetPermissionsByRoleID :many
SELECT p.id, p.action, p.resource_id
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
`

func (q *Queries) GetPermissionsByRoleID(ctx context.Context, roleID pgtype.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getPermissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Action, &i.ResourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourceByCode = `-- name: GetResourceByCode :one
SELECT id, code FROM resources WHERE code = $1
`

func (q *Queries) GetResourceByCode(ctx context.Context, code string) (Resource, error) {
	row := q.db.QueryRow(ctx, getResourceByCode, code)
	var i Resource
	err := row.Scan(&i.ID, &i.Code)
	return i, err
}

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT id, code FROM roles WHERE code = $1
`

func (q *Queries) GetRoleByCode(ctx context.Context, code string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByCode, code)
	var i Role
	err := row.Scan(&i.ID, &i.Code)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, role_id, blocked FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.RoleID,
		&i.Blocked,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password, role_id, blocked FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.RoleID,
		&i.Blocked,
	)
	return i, err
}
